version: '3'

services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cephas:
    build:
      context: .
    image: cephas:latest
    container_name: cephas
    environment:
      CEPHAS_SERVER_LISTEN_HOST: '0.0.0.0'
      CEPHAS_DB_HOST: mongodb
      CEPHAS_DB_USER: root
      CEPHAS_DB_PASS: example
    ports:
      - "8080:8080"
